import 'dart:ui';

import 'package:flutter/material.dart';

/// Generated by AssetsRefGenerator on 2020/04/03
class Res {
  static const String ic_citycard_more = "assets/3.0x/ic_citycard_more.png";




  static Color colorDivide = Colors.grey[200];
  static Color colorBlue = Colors.blue;
  static Color colorBlueFont = Colors.blue[300];
  static Color colorWhite = Colors.white;
  static Color colorBaseTitle = Colors.black87;
  static Color colorSubTitle = Colors.black38;
  static Color colorContent = Colors.grey;

}
